development:
  adapter: postgresql
  database: yeahdudeimgonna_com_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  database: yeahdudeimgonna_com_test
  pool: 5
  host: localhost
